name: Bug report
description: File a bug report
labels: [bug]
title: "[Bug] "
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List clear steps.
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Attach relevant logs or images.
  - type: input
    id: version
    attributes:
      label: App version
      placeholder: e.g., 1.0.0
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: macOS 14 / Windows 11 / Ubuntu 22.04
    validations:
      required: true
