name: Feature request
description: Suggest an idea or enhancement
labels: [enhancement]
title: "[Request] "
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What do you want to happen?
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What user problem does this address?
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
  - type: textarea
    id: notes
    attributes:
      label: Additional context
